name: TF-Deploy-testing
run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Authenticate to Google Cloud
        id: auth  # This ID is required for accessing outputs in the 0auth access token step
        uses: google-github-actions/auth@v2
        with:
            token_format: "access_token"
            workload_identity_provider: "projects/296888346216/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/github-actions-provider"
            service_account: "challenge-terraform-sa@andras-cv-challenge.iam.gserviceaccount.com"
    
      - name: Configure gcloud for ADC
        run: gcloud auth application-default login --quiet
        
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Checkout-repo
        uses: actions/checkout@v1

      - name: Terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform-start
        run: |
          terraform init
          terraform fmt --recursive
          terraform validate
          terraform plan
      - name: terraform deploy
        run: | 
            terraform apply -auto-approve
            