name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/296888346216/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/github-actions-provider'
        service_account: 'challenge-terraform-sa@andras-cv-challenge.iam.gserviceaccount.com'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Cypress e2e tests
      uses: cypress-io/github-actions@v6.9.0
      with:
        run: npx cypress run
        env:
        NODE_OPTIONS: "--no-experimental-require-module --no-experimental-detect-module"